runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /send_mail
  script: send_mail.app
- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
- url: .*
  script: main.app

